-- VHDL Entity riscvio_lib.alu_b_mux.symbol
--
-- Created:
--          by - eyasi.UNKNOWN (MEISTERKNECHT)
--          at - 12:38:24 20.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY alu_b_mux IS
   PORT( 
      alu_b_in_sel : IN     alu_in_sel_T;
      imm_dc       : IN     word_T;
      raux_dc      : IN     raux_T;
      rdat_dc      : IN     rdat_T;
      rptr_dc      : IN     rptr_T;
      b            : OUT    word_T
   );

-- Declarations

END alu_b_mux ;

