-- VHDL Entity riscvio_lib.at_reg.generatedInstance
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 13:36:37 09.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY at_reg IS
   PORT( 
      alu_out_at : IN     word_T;
      clk        : IN     std_logic;
      ctrl_at    : IN     ctrl_sig_T;
      reg_rd_at  : IN     reg_T;
      reg_rd_wb  : OUT    reg_T;
      reg_rs1_at : IN     reg_T;
      reg_rs2_at : IN     reg_T;
      res_n      : IN     std_logic
   );

END at_reg ;

