-- VHDL Entity riscvio_lib.at_reg.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 14:01:20 09.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY at_reg IS
   PORT( 
      alu_out_at : IN     word_T;
      clk        : IN     std_logic;
      ctrl_at    : IN     ctrl_sig_T;
      reg_rd_at  : IN     reg_T;
      reg_rs1_at : IN     reg_T;
      reg_rs2_at : IN     reg_T;
      res_n      : IN     std_logic;
      reg_rd_wb  : OUT    reg_T
   );

-- Declarations

END at_reg ;

