-- VHDL Entity riscvio_lib.at_reg.interface
--
-- Created:
--          by - leylknci.meyer (pc024)
--          at - 18:08:19 05/22/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY at_reg IS
   PORT( 
      alu_out_me : IN     word_T;
      clk        : IN     std_logic;
      ctrl_me    : IN     ctrl_sig_T;
      imm_me     : IN     word_T;
      raux_me    : IN     raux_T;
      rdat_me    : IN     rdat_T;
      rdst_ix_me : IN     reg_ix_T;
      res_n      : IN     std_logic;
      rptr_me    : IN     rptr_T;
      rd_wb      : OUT    reg_T
   );

-- Declarations

END at_reg ;

