-- VHDL Entity riscvio_lib.attr_load_unit.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 15:42:28 15.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY attr_load_unit IS
   PORT( 
      at_mode_me    : IN     at_mode_T;
      mem_out_me_uq : IN     word_T;
      ram_rdata_at  : IN     std_logic_vector (63 DOWNTO 0);
      dt_at_u       : OUT    word_T;
      pi_at_u       : OUT    word_T;
      ram_addr_at   : OUT    std_logic_vector (8 DOWNTO 0)
   );

-- Declarations

END attr_load_unit ;

