-- VHDL Entity riscvio_lib.block_ram_if.symbol
--
-- Created:
--          by - rbnlux.ckoehler (pc038)
--          at - 16:59:36 06/05/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY block_ram_if IS
   PORT( 
      addr           : IN     word_T;
      dram_q_a       : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      raux           : IN     raux_T;
      rptr           : IN     rptr_T;
      dram_address_a : OUT    STD_LOGIC_VECTOR (9 DOWNTO 0);
      dram_byteena_a : OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);
      dram_data_a    : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);
      dram_wren_a    : OUT    STD_LOGIC;
      mem_out        : OUT    word_T
   );

-- Declarations

END block_ram_if ;

