-- VHDL Entity audiotest_lib.clk_res_gen_var.symbol
--
-- Created:
--          by - st167825.st167825 (pc023)
--          at - 10:23:53 02/06/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY clk_res_gen_var IS
   GENERIC( 
      ONTIME    : time := 10 ns;
      OFFTIME   : time := 10 ns;
      RESETTIME : time := 35 ns
   );
   PORT( 
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );

-- Declarations

END clk_res_gen_var ;

