-- VHDL Entity riscvio_lib.clr_ptrs_fsm.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc038)
--          at - 18:13:03 06/05/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY clr_ptrs_fsm IS
   PORT( 
      alu_out_ex      : IN     word_T;
      clk             : IN     std_logic;
      ctrl_ex         : IN     ctrl_sig_T;
      rdst_ix_ex      : IN     reg_ix_T;
      res_n           : IN     std_logic;
      rptr_ex         : IN     rptr_T;
      rptr_ex_u       : IN     rptr_T;
      clr_addr        : OUT    word_T;
      clr_pgu_mode_me : OUT    boolean;
      clr_stall       : OUT    boolean;
      clr_wr          : OUT    boolean
   );

-- Declarations

END clr_ptrs_fsm ;

