-- VHDL Entity riscvio_lib.clr_ptrs_fsm.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 12:04:10 09.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY clr_ptrs_fsm IS
   PORT( 
      alu_out_ex : IN     word_T;
      clk        : IN     std_logic;
      ctrl_ex    : IN     ctrl_sig_T;
      end_addr   : IN     word_T;
      res_n      : IN     std_logic;
      clr_addr   : OUT    word_T;
      clr_stall  : OUT    boolean;
      clr_wr     : OUT    boolean
   );

-- Declarations

END clr_ptrs_fsm ;

