-- VHDL Entity riscvio_lib.clr_ptrs_fsm.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 18:11:38 06/12/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY clr_ptrs_fsm IS
   PORT( 
      alu_out_ex : IN     word_T;
      clk        : IN     std_logic;
      ctrl_ex    : IN     ctrl_sig_T;
      end_addr   : IN     word_T;
      imm_ex     : IN     word_T;
      raux_ex    : IN     raux_T;
      rdat_ex    : IN     rdat_T;
      res_n      : IN     std_logic;
      rptr_ex    : IN     rptr_T;
      clr_addr   : OUT    word_T;
      clr_data   : OUT    word_T;
      clr_stall  : OUT    boolean;
      clr_wr     : OUT    boolean
   );

-- Declarations

END clr_ptrs_fsm ;

