-- VHDL Entity riscvio_lib.csr_unit.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 16:58:33 05/29/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY csr_unit IS
   PORT( 
      clk     : IN     std_logic;
      csr_ix  : IN     csr_ix_T;
      rd_wb   : IN     reg_T;
      res_n   : IN     std_logic;
      csr_val : OUT    word_T
   );

-- Declarations

END csr_unit ;

