-- VHDL Entity riscvio_lib.csr_rf_mux.interface
--
-- Created:
--          by - leylknci.meyer (pc024)
--          at - 14:51:05 07/01/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
USE riscvio_lib.pipeline.all;

ENTITY csr_rf_mux IS
   PORT( 
      csr_reg   : IN     reg_mem_T;
      raux_rf   : IN     raux_T;
      rdat_ix   : IN     reg_nbr_T;
      rdat_rf   : IN     rdat_T;
      rptr_ix   : IN     reg_nbr_T;
      rptr_rf   : IN     rptr_T;
      raux_dc_u : OUT    raux_T;
      rdat_dc_u : OUT    rdat_T;
      rptr_dc_u : OUT    rptr_T
   );

-- Declarations

END csr_rf_mux ;

