-- VHDL Entity riscvio_lib.dc_reg.interface
--
-- Created:
--          by - leylknci.meyer (pc024)
--          at - 18:23:46 05/22/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY dc_reg IS
   PORT( 
      clk          : IN     std_logic;
      ctrl_dc_u    : IN     ctrl_sig_t;
      dbta_valid   : IN     boolean;
      imm_dc_u     : IN     word_T;
      pc_if        : IN     word_T;
      raux_dc_u    : IN     raux_T;
      rdat_dc_u    : IN     rdat_T;
      rdst_ix_dc_u : IN     reg_ix_T;
      res_n        : IN     std_logic;
      rptr_dc_u    : IN     rptr_T;
      alu_a_in_sel : OUT    alu_in_sel_T;
      alu_b_in_sel : OUT    alu_in_sel_T;
      alu_mode_dc  : OUT    alu_mode_T;
      ctrl_dc      : OUT    ctrl_sig_T;
      imm_dc       : OUT    word_T;
      pc_dc        : OUT    word_T;
      raux_dc      : OUT    raux_T;
      rdat_dc      : OUT    rdat_T;
      rdst_ix_dc   : OUT    reg_ix_T;
      rptr_dc      : OUT    rptr_T
   );

-- Declarations

END dc_reg ;

