-- VHDL Entity riscvio_lib.dc_reg.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 11:58:02 05.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY dc_reg IS
   PORT( 
      clk           : IN     std_logic;
      if_ctrl       : IN     ctrl_signals_T;
      reg_a         : IN     register_T;
      reg_b         : IN     register_T;
      reg_c         : IN     register_T;
      res_n         : IN     std_logic;
      dc_alu_mode   : OUT    alu_mode_T;
      dc_ctrl       : OUT    ctrl_signals_T;
      dc_imm        : OUT    imm_12_bit_T;
      dc_reg_a_data : OUT    dword_T;
      dc_reg_b_data : OUT    dword_T;
      dc_use_imm    : OUT    boolean
   );

-- Declarations

END dc_reg ;

