-- VHDL Entity riscvio_lib.dcbr_wraccess_mux.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 18:11:38 06/12/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY dcbr_wraccess_mux IS
   PORT( 
      clr_addr       : IN     word_T;
      clr_data       : IN     word_T;
      clr_wr         : IN     boolean;
      dram_address_a : IN     word_T;
      dram_byteena_a : IN     STD_LOGIC_VECTOR (3 DOWNTO 0);
      dram_data_a    : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      dram_wren_a    : IN     STD_LOGIC;
      ram_addr_me    : OUT    STD_LOGIC_VECTOR (9 DOWNTO 0);
      ram_byteena_me : OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);
      ram_wdata_me   : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);
      ram_wren_me    : OUT    STD_LOGIC
   );

-- Declarations

END dcbr_wraccess_mux ;

