-- VHDL Entity riscvio_lib.dcbr_wraccess_mux.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 00:06:16 09.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY dcbr_wraccess_mux IS
   PORT( 
      clr_addr           : IN     word_T;
      clr_wr             : IN     boolean;
      dram_address_a     : IN     word_T;
      dram_byteena_a     : IN     STD_LOGIC_VECTOR (3 DOWNTO 0);
      dram_data_a        : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      dram_wren_a        : IN     STD_LOGIC;
      data_ram_address_a : OUT    STD_LOGIC_VECTOR (9 DOWNTO 0);
      data_ram_byteena_a : OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);
      data_ram_data_a    : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);
      data_ram_wren_a    : OUT    STD_LOGIC
   );

-- Declarations

END dcbr_wraccess_mux ;

