-- VHDL Entity riscvio_lib.decoder_tb.symbol
--
-- Created:
--          by - leylknci.meyer (pc038)
--          at - 18:43:48 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY decoder_tb IS
-- Declarations

END decoder_tb ;

