-- VHDL Entity riscvio_lib.decoder.interface
--
-- Created:
--          by - leylknci.meyer (pc038)
--          at - 19:03:12 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY decoder IS
   PORT( 
      pc          : IN     pc_T;
      instruction : IN     word_T;

      rdat_ix     : OUT    reg_ix_T;
      rptr_ix     : OUT    reg_ix_T;
      raux_ix     : OUT    reg_ix_T;

      csr_ix      : OUT    csr_ix_T;

      rdst_ix     : OUT    reg_ix_T;
      imm         : OUT    word_T;

      ctr_sig     : OUT    ctrl_sig_t;
      sbt_valid   : OUT    boolean;
      sbt         : OUT    pc_T;

      exc         : OUT    exc_cause_T
   );

-- Declarations

END decoder ;

