-- VHDL Entity riscvio_lib.decoder.interface
--
-- Created:
--          by - leylknci.meyer (pc038)
--          at - 19:03:12 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY decoder IS
   PORT( 
      pc          : IN     word_T;
      instruction : IN     word_T;
      ctr_sig     : OUT    ctrl_sig_t;
      rs1_ix      : OUT    reg_ix_T;
      rs2_ix      : OUT    reg_ix_T;
      rd_ix       : OUT    reg_ix_T;

      imm_as_reg  : OUT    reg_T;
      sbta_valid  : OUT boolean;
      sbta        : OUT word_T
   );

-- Declarations

END decoder ;

