-- VHDL Entity riscvio_lib.decoder_tester.interface
--
-- Created:
--          by - leylknci.meyer (pc038)
--          at - 19:00:45 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY decoder_tester IS
   PORT( 
      clk         : IN     std_logic;
      res_n       : IN     std_logic;
      instruction : OUT    std_logic_vector (31 DOWNTO 0)
   );

-- Declarations

END decoder_tester ;

