-- VHDL Entity riscvio_lib.ex_reg.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 18:06:52 05/15/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY ex_reg IS
   PORT( 
      alu_out_ex_u : IN     word_T;
      clk          : IN     std_logic;
      ctrl_ex      : IN     ctrl_sig_T;
      rd_ex        : IN     reg_T;
      res_n        : IN     std_logic;
      rs1_ex       : IN     reg_T;
      rs2_ex       : IN     reg_T;
      alu_out_me   : OUT    word_T;
      ctrl_me      : OUT    ctrl_sig_T;
      rd_me        : OUT    reg_T;
      rs1_me       : OUT    reg_T;
      rs2_me       : OUT    reg_T
   );

-- Declarations

END ex_reg ;

