-- VHDL Entity riscvio_lib.ex_reg.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 15:52:12 15.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY ex_reg IS
   PORT( 
      alu_out_ex_u   : IN     word_T;
      clk            : IN     std_logic;
      ctrl_dc        : IN     ctrl_sig_T;
      imm_dc         : IN     word_T;
      obj_init_stall : IN     boolean;
      ptr_addr_ex_u  : IN     word_T;
      raux_dc        : IN     raux_T;
      rdat_dc        : IN     rdat_T;
      rdst_ix_dc     : IN     reg_ix_T;
      res_n          : IN     std_logic;
      rptr_dc        : IN     rptr_T;
      alu_out_dc_uq  : OUT    word_T;
      alu_out_ex     : OUT    word_T;
      ctrl_ex        : OUT    ctrl_sig_T;
      imm_ex         : OUT    word_T;
      me_mode_dc_uq  : OUT    mem_mode_t;
      me_mode_ex     : OUT    mem_mode_T;
      raux_dc_uq     : OUT    raux_T;
      raux_ex        : OUT    raux_T;
      rdat_ex        : OUT    rdat_T;
      rdst_ix_ex     : OUT    reg_ix_T;
      rptr_dc_uq     : OUT    rptr_T;
      rptr_ex        : OUT    rptr_T
   );

-- Declarations

END ex_reg ;

