-- VHDL Entity riscvio_lib.if_reg.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 13:58:51 09.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY if_reg IS
   PORT( 
      clk           : IN     std_logic;
      dbta_valid    : IN     boolean;
      if_instr_d    : IN     word_T;
      pc_current_pc : IN     word_T;
      res_n         : IN     std_logic;
      sbta_valid    : IN     boolean;
      if_instr      : OUT    word_T;
      pc_dc         : OUT    word_T
   );

-- Declarations

END if_reg ;

