-- VHDL Entity riscvio_lib.imm_mux.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 13:36:36 09.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY imm_mux IS
   PORT( 
      ctrl_dc_u    : IN     ctrl_sig_t;
      imm_as_reg   : IN     reg_T;
      reg_rs2      : IN     reg_T;
      reg_rs2_dc_u : OUT    reg_T
   );

-- Declarations

END imm_mux ;

