-- VHDL Entity riscvio_lib.imm_mux.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 14:26:22 09.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY imm_mux IS
   PORT( 
      ctrl_dc_u    : IN     ctrl_sig_t;
      imm_as_reg   : IN     reg_T;
      rd       : IN     reg_T;
      rs2      : IN     reg_T;
      rd_dc_u  : OUT    reg_T;
      rs2_dc_u : OUT    reg_T
   );

-- Declarations

END imm_mux ;

