-- VHDL Entity riscvio_lib.imm_mux.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 17:10:32 05/08/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY imm_mux IS
   PORT( 
      ctrl_dc_u    : IN     ctrl_sig_t;
      imm_as_reg   : IN     reg_T;
      reg_rs2      : IN     reg_T;
      reg_rs2_dc_u : OUT    reg_T
   );

-- Declarations

END imm_mux ;

