-- VHDL Entity riscvio_lib.me_reg.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 13:59:55 09.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY me_reg IS
   PORT( 
      alu_out_me : IN     word_T;
      clk        : IN     std_logic;
      ctrl_me    : IN     ctrl_sig_T;
      reg_rd_me  : IN     reg_T;
      reg_rs1_me : IN     reg_T;
      reg_rs2_me : IN     reg_T;
      res_n      : IN     std_logic;
      alu_out_at : OUT    word_T;
      ctrl_at    : OUT    ctrl_sig_T;
      reg_rd_at  : OUT    reg_T;
      reg_rs1_at : OUT    reg_T;
      reg_rs2_at : OUT    reg_T
   );

-- Declarations

END me_reg ;

