-- VHDL Entity riscvio_lib.me_reg.generatedInstance
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 17:11:32 01.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY me_reg IS
   PORT( 
      clk        : IN     std_logic;
      ex_alu_out : IN     dword_T;
      ex_ctrl    : IN     ctrl_signals_T;
      me_alu_out : OUT    dword_T;
      me_ctrl    : OUT    ctrl_signals_T;
      res_n      : IN     std_logic
   );

END me_reg ;

