-- VHDL Entity riscvio_lib.obj_init_fsm.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc023)
--          at - 09:32:04 06/13/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY obj_init_fsm IS
   PORT( 
      alu_out_ex     : IN     word_T;
      clk            : IN     std_logic;
      ctrl_ex        : IN     ctrl_sig_T;
      end_addr       : IN     word_T;
      imm_ex         : IN     word_T;
      raux_ex        : IN     raux_T;
      rdat_ex        : IN     rdat_T;
      res_n          : IN     std_logic;
      rptr_ex        : IN     rptr_T;
      obj_init_addr  : OUT    word_T;
      obj_init_data  : OUT    word_T;
      obj_init_stall : OUT    boolean;
      obj_init_wr    : OUT    boolean
   );

-- Declarations

END obj_init_fsm ;

