-- VHDL Entity riscvio_lib.pc_reg.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 17:11:11 01.05.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;

ENTITY pc_reg IS
   PORT( 
      clk           : IN     std_logic;
      current_pc_d  : IN     dword_T;
      res_n         : IN     std_logic;
      pc_current_pc : OUT    dword_T
   );

-- Declarations

END pc_reg ;

