-- VHDL Entity riscvio_lib.pc_reg.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 18:13:22 05/15/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY pc_reg IS
   PORT( 
      clk           : IN     std_logic;
      current_pc_d  : IN     word_T;
      res_n         : IN     std_logic;
      pc_current_pc : OUT    word_T
   );

-- Declarations

END pc_reg ;

