-- VHDL Entity riscvio_lib.pgu.symbol
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 15:29:54 16.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY pgu IS
   PORT( 
      imm      : IN     word_T;
      pgu_mode : IN     pgu_mode_T;
      raux     : IN     raux_T;
      rdat     : IN     rdat_T;
      rptr     : IN     rptr_T;
      rdst_ix  : IN     reg_ix_T;
      ptr      : OUT    reg_mem_T;
      frame_type_exception: OUT boolean;
      state_error_exception: OUT boolean;
      index_out_of_bounds_exception: OUT boolean;
   );

-- Declarations

END pgu ;

