-- VHDL Entity riscvio_lib.pgu.symbol
--
-- Created:
--          by - rbnlux.ckoehler (pc038)
--          at - 15:17:49 06/05/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;

ENTITY pgu IS
   PORT( 
      imm      : IN     word_T;
      pgu_mode : IN     pgu_mode_T;
      raux     : IN     raux_T;
      rdat     : IN     rdat_T;
      rptr     : IN     rptr_T;
      addr     : OUT    word_T
   );

-- Declarations

END pgu ;

