--
-- VHDL Architecture riscvio_lib.riscvio.struct
--
-- Created:
--          by - rbnlux.ckoehler (pc023)
--          at - 09:32:04 06/13/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;


ARCHITECTURE struct OF riscvio IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL a               : word_T;
   SIGNAL alu_a_in_sel_dc : alu_in_sel_T;
   SIGNAL alu_b_in_sel_dc : alu_in_sel_T;
   SIGNAL alu_mode_dc     : alu_mode_T;
   SIGNAL alu_out_dc_uq   : word_T;
   SIGNAL alu_out_ex      : word_T;
   SIGNAL alu_out_ex_u    : word_T;
   SIGNAL alu_out_me      : word_T;
   SIGNAL at_mode_me      : at_mode_T;
   SIGNAL b               : word_T;
   SIGNAL byteena_b       : STD_LOGIC_VECTOR(7 DOWNTO 0) := (OTHERS => '1');
   SIGNAL csr_ix          : csr_ix_T;
   SIGNAL csr_val         : word_T;
   SIGNAL ctrl_dc         : ctrl_sig_T;
   SIGNAL ctrl_dc_u       : ctrl_sig_t;
   SIGNAL ctrl_dc_uq      : ctrl_sig_t;
   SIGNAL ctrl_ex         : ctrl_sig_T;
   SIGNAL ctrl_me         : ctrl_sig_T;
   SIGNAL current_pc_d    : pc_T;
   SIGNAL data_b          : STD_LOGIC_VECTOR(63 DOWNTO 0);
   SIGNAL dbt             : pc_T;
   SIGNAL dbt_valid       : boolean;
   SIGNAL dram_address_a  : word_T;
   SIGNAL dram_byteena_a  : STD_LOGIC_VECTOR(3 DOWNTO 0);
   SIGNAL dram_data_a     : STD_LOGIC_VECTOR(31 DOWNTO 0);
   SIGNAL dram_wren_a     : STD_LOGIC;
   SIGNAL dt_at_u         : word_T;
   SIGNAL end_addr        : word_T;
   SIGNAL flags           : alu_flags_T;
   SIGNAL if_instr        : word_T;
   SIGNAL if_instr_d      : word_T;
   SIGNAL imm_dc          : word_T;
   SIGNAL imm_dc_u        : word_T;
   SIGNAL imm_ex          : word_T;
   SIGNAL imm_me          : word_T;
   SIGNAL incremented_pc  : pc_T;
   SIGNAL mem_out_me      : word_T;
   SIGNAL mem_out_me_u    : word_T;
   SIGNAL mem_out_me_uq   : word_T;
   SIGNAL obj_init_addr   : word_T;
   SIGNAL obj_init_data   : word_T;
   SIGNAL obj_init_stall  : boolean;
   SIGNAL obj_init_wr     : boolean;
   SIGNAL pc_current_pc   : pc_T;
   SIGNAL pc_dc           : pc_T;
   SIGNAL pc_if           : pc_T;
   SIGNAL pgu_mode_dc     : pgu_mode_T;
   SIGNAL pi_at_u         : word_T;
   SIGNAL ptr_addr_ex_u   : word_T;
   SIGNAL ram_addr_at     : std_logic_vector(8 DOWNTO 0);
   SIGNAL ram_addr_me     : STD_LOGIC_VECTOR(9 DOWNTO 0);
   SIGNAL ram_byteena_me  : STD_LOGIC_VECTOR(3 DOWNTO 0) := (OTHERS => '1');
   SIGNAL ram_rdata_at    : std_logic_vector(63 DOWNTO 0);
   SIGNAL ram_rdata_me    : STD_LOGIC_VECTOR(31 DOWNTO 0);
   SIGNAL ram_wdata_me    : STD_LOGIC_VECTOR(31 DOWNTO 0);
   SIGNAL ram_wren_me     : STD_LOGIC                    := '0';
   SIGNAL raux_dc         : raux_T;
   SIGNAL raux_dc_u       : raux_T;
   SIGNAL raux_dc_uq      : raux_T;
   SIGNAL raux_ex         : raux_T;
   SIGNAL raux_ix         : reg_ix_T;
   SIGNAL raux_me         : raux_T;
   SIGNAL raux_rf         : raux_T;
   SIGNAL rd_wb           : reg_wb_T;
   SIGNAL rdat_dc         : rdat_T;
   SIGNAL rdat_dc_u       : rdat_T;
   SIGNAL rdat_ex         : rdat_T;
   SIGNAL rdat_ix         : reg_ix_T;
   SIGNAL rdat_me         : rdat_T;
   SIGNAL rdat_rf         : rdat_T;
   SIGNAL rdst_ix_dc      : reg_ix_T;
   SIGNAL rdst_ix_dc_u    : reg_ix_T;
   SIGNAL rdst_ix_ex      : reg_ix_T;
   SIGNAL rdst_ix_me      : reg_ix_T;
   SIGNAL rptr_dc         : rptr_T;
   SIGNAL rptr_dc_u       : rptr_T;
   SIGNAL rptr_dc_uq      : rptr_T;
   SIGNAL rptr_ex         : rptr_T;
   SIGNAL rptr_ix         : reg_ix_T;
   SIGNAL rptr_me         : rptr_T;
   SIGNAL rptr_rf         : rptr_T;
   SIGNAL sbt             : pc_T;
   SIGNAL sbt_valid       : boolean;
   SIGNAL wren_b          : STD_LOGIC                    := '0';


   -- Component Declarations
   COMPONENT alu
   PORT (
      a       : IN     word_T ;
      b       : IN     word_T ;
      mode    : IN     alu_mode_T ;
      alu_out : OUT    word_T ;
      flags   : OUT    alu_flags_T 
   );
   END COMPONENT;
   COMPONENT alu_a_mux
   PORT (
      alu_a_in_sel : IN     alu_in_sel_T ;
      raux_dc      : IN     raux_T ;
      rdat_dc      : IN     rdat_T ;
      rptr_dc      : IN     rptr_T ;
      a            : OUT    word_T 
   );
   END COMPONENT;
   COMPONENT alu_b_mux
   PORT (
      alu_b_in_sel : IN     alu_in_sel_T ;
      imm_dc       : IN     word_T ;
      raux_dc      : IN     raux_T ;
      rdat_dc      : IN     rdat_T ;
      rptr_dc      : IN     rptr_T ;
      b            : OUT    word_T 
   );
   END COMPONENT;
   COMPONENT at_reg
   PORT (
      alu_out_me     : IN     word_T ;
      clk            : IN     std_logic ;
      ctrl_me        : IN     ctrl_sig_T ;
      dt_at_u        : IN     word_T ;
      imm_me         : IN     word_T ;
      mem_out_me     : IN     word_T ;
      obj_init_stall : IN     boolean ;
      pi_at_u        : IN     word_T ;
      raux_me        : IN     raux_T ;
      rdat_me        : IN     rdat_T ;
      rdst_ix_me     : IN     reg_ix_T ;
      res_n          : IN     std_logic ;
      rptr_me        : IN     rptr_T ;
      rd_wb          : OUT    reg_wb_T 
   );
   END COMPONENT;
   COMPONENT attr_load_unit
   PORT (
      at_mode_me    : IN     at_mode_T ;
      mem_out_me_uq : IN     word_T ;
      ram_rdata_at  : IN     std_logic_vector (63 DOWNTO 0);
      dt_at_u       : OUT    word_T ;
      pi_at_u       : OUT    word_T ;
      ram_addr_at   : OUT    std_logic_vector (8 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT block_ram_if
   PORT (
      addr           : IN     word_T ;
      dram_q_a       : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      mode           : IN     ctrl_sig_T ;
      mode_u         : IN     ctrl_sig_T ;
      raux           : IN     raux_T ;
      rptr           : IN     rptr_T ;
      dram_address_a : OUT    word_T ;
      dram_byteena_a : OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);
      dram_data_a    : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);
      dram_wren_a    : OUT    STD_LOGIC ;
      mem_out        : OUT    word_T 
   );
   END COMPONENT;
   COMPONENT clr_ptr_end_addr_mux
   PORT (
      raux_ex    : IN     raux_T ;
      rdst_ix_ex : IN     reg_ix_T ;
      rptr_ex    : IN     rptr_T ;
      end_addr   : OUT    word_T 
   );
   END COMPONENT;
   COMPONENT csr_rf_mux
   PORT (
      csr_val   : IN     word_T ;
      raux_rf   : IN     raux_T ;
      rdat_ix   : IN     reg_ix_T ;
      rdat_rf   : IN     rdat_T ;
      rptr_ix   : IN     reg_ix_T ;
      rptr_rf   : IN     rptr_T ;
      raux_dc_u : OUT    raux_T ;
      rdat_dc_u : OUT    rdat_T ;
      rptr_dc_u : OUT    rptr_T 
   );
   END COMPONENT;
   COMPONENT csr_unit
   PORT (
      clk     : IN     std_logic ;
      csr_ix  : IN     csr_ix_T ;
      rd_wb   : IN     reg_wb_T ;
      res_n   : IN     std_logic ;
      csr_val : OUT    word_T 
   );
   END COMPONENT;
   COMPONENT dc_reg
   PORT (
      clk             : IN     std_logic ;
      ctrl_dc_u       : IN     ctrl_sig_t ;
      dbt_valid       : IN     boolean ;
      imm_dc_u        : IN     word_T ;
      obj_init_stall  : IN     boolean ;
      pc_if           : IN     pc_T ;
      raux_dc_u       : IN     raux_T ;
      rdat_dc_u       : IN     rdat_T ;
      rdst_ix_dc_u    : IN     reg_ix_T ;
      res_n           : IN     std_logic ;
      rptr_dc_u       : IN     rptr_T ;
      alu_a_in_sel_dc : OUT    alu_in_sel_T ;
      alu_b_in_sel_dc : OUT    alu_in_sel_T ;
      alu_mode_dc     : OUT    alu_mode_T ;
      ctrl_dc         : OUT    ctrl_sig_T ;
      imm_dc          : OUT    word_T ;
      pc_dc           : OUT    pc_T ;
      pgu_mode_dc     : OUT    pgu_mode_T ;
      raux_dc         : OUT    raux_T ;
      rdat_dc         : OUT    rdat_T ;
      rdst_ix_dc      : OUT    reg_ix_T ;
      rptr_dc         : OUT    rptr_T 
   );
   END COMPONENT;
   COMPONENT dcbr_wraccess_mux
   PORT (
      dram_address_a : IN     word_T ;
      dram_byteena_a : IN     STD_LOGIC_VECTOR (3 DOWNTO 0);
      dram_data_a    : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      dram_wren_a    : IN     STD_LOGIC ;
      obj_init_addr  : IN     word_T ;
      obj_init_data  : IN     word_T ;
      obj_init_wr    : IN     boolean ;
      ram_addr_me    : OUT    STD_LOGIC_VECTOR (9 DOWNTO 0);
      ram_byteena_me : OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);
      ram_wdata_me   : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);
      ram_wren_me    : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT decoder
   PORT (
      instruction : IN     word_T;
      pc          : IN     pc_T;
      csr_ix      : OUT    csr_ix_T;
      ctr_sig     : OUT    ctrl_sig_t;
      imm         : OUT    word_T;
      raux_ix     : OUT    reg_ix_T;
      rdat_ix     : OUT    reg_ix_T;
      rdst_ix     : OUT    reg_ix_T;
      rptr_ix     : OUT    reg_ix_T;
      sbt         : OUT    pc_T;
      sbt_valid   : OUT    boolean
   );
   END COMPONENT;
   COMPONENT dual_port_memory
   PORT (
      address_a : IN     STD_LOGIC_VECTOR (9 DOWNTO 0);
      address_b : IN     STD_LOGIC_VECTOR (8 DOWNTO 0);
      byteena_a : IN     STD_LOGIC_VECTOR (3 DOWNTO 0) := (OTHERS => '1');
      byteena_b : IN     STD_LOGIC_VECTOR (7 DOWNTO 0) := (OTHERS => '1');
      clock     : IN     STD_LOGIC                     := '1';
      data_a    : IN     STD_LOGIC_VECTOR (31 DOWNTO 0);
      data_b    : IN     STD_LOGIC_VECTOR (63 DOWNTO 0);
      wren_a    : IN     STD_LOGIC                     := '0';
      wren_b    : IN     STD_LOGIC                     := '0';
      q_a       : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0);
      q_b       : OUT    STD_LOGIC_VECTOR (63 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT dyn_branch_unit
   PORT (
      alu_flags : IN     alu_flags_T;
      ctrl_sig  : IN     ctrl_sig_T;
      imm       : IN     word_T;
      pc        : IN     pc_T;
      dbt       : OUT    pc_T;
      dbt_valid : OUT    boolean
   );
   END COMPONENT;
   COMPONENT ex_reg
   PORT (
      alu_out_ex_u   : IN     word_T ;
      clk            : IN     std_logic ;
      ctrl_dc        : IN     ctrl_sig_T ;
      imm_dc         : IN     word_T ;
      obj_init_stall : IN     boolean ;
      ptr_addr_ex_u  : IN     word_T ;
      raux_dc        : IN     raux_T ;
      rdat_dc        : IN     rdat_T ;
      rdst_ix_dc     : IN     reg_ix_T ;
      res_n          : IN     std_logic ;
      rptr_dc        : IN     rptr_T ;
      alu_out_dc_uq  : OUT    word_T ;
      alu_out_ex     : OUT    word_T ;
      ctrl_dc_uq     : OUT    ctrl_sig_t ;
      ctrl_ex        : OUT    ctrl_sig_T ;
      imm_ex         : OUT    word_T ;
      raux_dc_uq     : OUT    raux_T ;
      raux_ex        : OUT    raux_T ;
      rdat_ex        : OUT    rdat_T ;
      rdst_ix_ex     : OUT    reg_ix_T ;
      rptr_dc_uq     : OUT    rptr_T ;
      rptr_ex        : OUT    rptr_T 
   );
   END COMPONENT;
   COMPONENT if_reg
   PORT (
      clk            : IN     std_logic ;
      dbt_valid      : IN     boolean ;
      if_instr_d     : IN     word_T ;
      obj_init_stall : IN     boolean ;
      pc_current_pc  : IN     pc_T ;
      res_n          : IN     std_logic ;
      sbt_valid      : IN     boolean ;
      if_instr       : OUT    word_T ;
      pc_if          : OUT    pc_T 
   );
   END COMPONENT;
   COMPONENT instruction_rom
   PORT (
      clock : IN     STD_LOGIC  := '1';
      pc    : IN     pc_T;
      q     : OUT    STD_LOGIC_VECTOR (31 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT me_reg
   PORT (
      alu_out_ex     : IN     word_T ;
      clk            : IN     std_logic ;
      ctrl_ex        : IN     ctrl_sig_T ;
      imm_ex         : IN     word_T ;
      mem_out_me_u   : IN     word_T ;
      obj_init_stall : IN     boolean ;
      raux_ex        : IN     raux_T ;
      rdat_ex        : IN     rdat_T ;
      rdst_ix_ex     : IN     reg_ix_T ;
      res_n          : IN     std_logic ;
      rptr_ex        : IN     rptr_T ;
      alu_out_me     : OUT    word_T ;
      at_mode_me     : OUT    at_mode_T ;
      ctrl_me        : OUT    ctrl_sig_T ;
      imm_me         : OUT    word_T ;
      mem_out_me     : OUT    word_T ;
      mem_out_me_uq  : OUT    word_T ;
      raux_me        : OUT    raux_T ;
      rdat_me        : OUT    rdat_T ;
      rdst_ix_me     : OUT    reg_ix_T ;
      rptr_me        : OUT    rptr_T 
   );
   END COMPONENT;
   COMPONENT next_pc_mux
   PORT (
      dbta_valid        : IN     boolean;
      dynamic_branch_pc : IN     pc_T;
      incremented_pc    : IN     pc_T;
      sbta_valid        : IN     boolean;
      static_branch_pc  : IN     pc_T;
      next_pc           : OUT    pc_T
   );
   END COMPONENT;
   COMPONENT obj_init_fsm
   PORT (
      alu_out_ex     : IN     word_T ;
      clk            : IN     std_logic ;
      ctrl_ex        : IN     ctrl_sig_T ;
      end_addr       : IN     word_T ;
      imm_ex         : IN     word_T ;
      raux_ex        : IN     raux_T ;
      rdat_ex        : IN     rdat_T ;
      res_n          : IN     std_logic ;
      rptr_ex        : IN     rptr_T ;
      obj_init_addr  : OUT    word_T ;
      obj_init_data  : OUT    word_T ;
      obj_init_stall : OUT    boolean ;
      obj_init_wr    : OUT    boolean 
   );
   END COMPONENT;
   COMPONENT pc_incrementer
   PORT (
      pc      : IN     pc_T;
      next_pc : OUT    pc_T
   );
   END COMPONENT;
   COMPONENT pc_reg
   PORT (
      clk            : IN     std_logic ;
      current_pc_d   : IN     pc_T ;
      obj_init_stall : IN     boolean ;
      res_n          : IN     std_logic ;
      pc_current_pc  : OUT    pc_T 
   );
   END COMPONENT;
   COMPONENT pgu
   PORT (
      imm      : IN     word_T ;
      pgu_mode : IN     pgu_mode_T ;
      raux     : IN     raux_T ;
      rdat     : IN     rdat_T ;
      rptr     : IN     rptr_T ;
      addr     : OUT    word_T 
   );
   END COMPONENT;
   COMPONENT register_file
   PORT (
      clk     : IN     std_logic;
      raux_ix : IN     reg_ix_T;
      rd_wb   : IN     reg_wb_T;
      rdat_ix : IN     reg_ix_T;
      res_n   : IN     std_logic;
      rptr_ix : IN     reg_ix_T;
      raux    : OUT    raux_T;
      rdat    : OUT    rdat_T;
      rptr    : OUT    rptr_T
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : alu USE ENTITY riscvio_lib.alu;
   FOR ALL : alu_a_mux USE ENTITY riscvio_lib.alu_a_mux;
   FOR ALL : alu_b_mux USE ENTITY riscvio_lib.alu_b_mux;
   FOR ALL : at_reg USE ENTITY riscvio_lib.at_reg;
   FOR ALL : attr_load_unit USE ENTITY riscvio_lib.attr_load_unit;
   FOR ALL : block_ram_if USE ENTITY riscvio_lib.block_ram_if;
   FOR ALL : clr_ptr_end_addr_mux USE ENTITY riscvio_lib.clr_ptr_end_addr_mux;
   FOR ALL : csr_rf_mux USE ENTITY riscvio_lib.csr_rf_mux;
   FOR ALL : csr_unit USE ENTITY riscvio_lib.csr_unit;
   FOR ALL : dc_reg USE ENTITY riscvio_lib.dc_reg;
   FOR ALL : dcbr_wraccess_mux USE ENTITY riscvio_lib.dcbr_wraccess_mux;
   FOR ALL : decoder USE ENTITY riscvio_lib.decoder;
   FOR ALL : dual_port_memory USE ENTITY riscvio_lib.dual_port_memory;
   FOR ALL : dyn_branch_unit USE ENTITY riscvio_lib.dyn_branch_unit;
   FOR ALL : ex_reg USE ENTITY riscvio_lib.ex_reg;
   FOR ALL : if_reg USE ENTITY riscvio_lib.if_reg;
   FOR ALL : instruction_rom USE ENTITY riscvio_lib.instruction_rom;
   FOR ALL : me_reg USE ENTITY riscvio_lib.me_reg;
   FOR ALL : next_pc_mux USE ENTITY riscvio_lib.next_pc_mux;
   FOR ALL : obj_init_fsm USE ENTITY riscvio_lib.obj_init_fsm;
   FOR ALL : pc_incrementer USE ENTITY riscvio_lib.pc_incrementer;
   FOR ALL : pc_reg USE ENTITY riscvio_lib.pc_reg;
   FOR ALL : pgu USE ENTITY riscvio_lib.pgu;
   FOR ALL : register_file USE ENTITY riscvio_lib.register_file;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1  
   byteena_b <= (others => '1');
   data_b <= (others => '0');
   wren_b <= '0';                                    


   -- Instance port mappings.
   alu_i : alu
      PORT MAP (
         a       => a,
         b       => b,
         mode    => alu_mode_dc,
         alu_out => alu_out_ex_u,
         flags   => flags
      );
   alu_a_mux_i : alu_a_mux
      PORT MAP (
         alu_a_in_sel => alu_a_in_sel_dc,
         raux_dc      => raux_dc,
         rdat_dc      => rdat_dc,
         rptr_dc      => rptr_dc,
         a            => a
      );
   alu_b_mux_i : alu_b_mux
      PORT MAP (
         alu_b_in_sel => alu_b_in_sel_dc,
         imm_dc       => imm_dc,
         raux_dc      => raux_dc,
         rdat_dc      => rdat_dc,
         rptr_dc      => rptr_dc,
         b            => b
      );
   at_reg_i : at_reg
      PORT MAP (
         alu_out_me     => alu_out_me,
         clk            => clk,
         ctrl_me        => ctrl_me,
         dt_at_u        => dt_at_u,
         imm_me         => imm_me,
         mem_out_me     => mem_out_me,
         obj_init_stall => obj_init_stall,
         pi_at_u        => pi_at_u,
         raux_me        => raux_me,
         rdat_me        => rdat_me,
         rdst_ix_me     => rdst_ix_me,
         res_n          => res_n,
         rptr_me        => rptr_me,
         rd_wb          => rd_wb
      );
   attr_ld_i : attr_load_unit
      PORT MAP (
         at_mode_me    => at_mode_me,
         mem_out_me_uq => mem_out_me_uq,
         ram_rdata_at  => ram_rdata_at,
         dt_at_u       => dt_at_u,
         pi_at_u       => pi_at_u,
         ram_addr_at   => ram_addr_at
      );
   block_ram_if_i : block_ram_if
      PORT MAP (
         addr           => alu_out_dc_uq,
         dram_q_a       => ram_rdata_me,
         mode           => ctrl_ex,
         mode_u         => ctrl_dc_uq,
         raux           => raux_dc_uq,
         rptr           => rptr_dc_uq,
         dram_address_a => dram_address_a,
         dram_byteena_a => dram_byteena_a,
         dram_data_a    => dram_data_a,
         dram_wren_a    => dram_wren_a,
         mem_out        => mem_out_me_u
      );
   clr_ptr_end_addr_mux_i : clr_ptr_end_addr_mux
      PORT MAP (
         raux_ex    => raux_ex,
         rdst_ix_ex => rdst_ix_ex,
         rptr_ex    => rptr_ex,
         end_addr   => end_addr
      );
   csr_rf_mux_i : csr_rf_mux
      PORT MAP (
         csr_val   => csr_val,
         raux_rf   => raux_rf,
         rdat_ix   => rdat_ix,
         rdat_rf   => rdat_rf,
         rptr_ix   => rptr_ix,
         rptr_rf   => rptr_rf,
         raux_dc_u => raux_dc_u,
         rdat_dc_u => rdat_dc_u,
         rptr_dc_u => rptr_dc_u
      );
   csr_unit_i : csr_unit
      PORT MAP (
         clk     => clk,
         csr_ix  => csr_ix,
         rd_wb   => rd_wb,
         res_n   => res_n,
         csr_val => csr_val
      );
   dc_reg_i : dc_reg
      PORT MAP (
         clk             => clk,
         ctrl_dc_u       => ctrl_dc_u,
         dbt_valid       => dbt_valid,
         imm_dc_u        => imm_dc_u,
         obj_init_stall  => obj_init_stall,
         pc_if           => pc_if,
         raux_dc_u       => raux_dc_u,
         rdat_dc_u       => rdat_dc_u,
         rdst_ix_dc_u    => rdst_ix_dc_u,
         res_n           => res_n,
         rptr_dc_u       => rptr_dc_u,
         alu_a_in_sel_dc => alu_a_in_sel_dc,
         alu_b_in_sel_dc => alu_b_in_sel_dc,
         alu_mode_dc     => alu_mode_dc,
         ctrl_dc         => ctrl_dc,
         imm_dc          => imm_dc,
         pc_dc           => pc_dc,
         pgu_mode_dc     => pgu_mode_dc,
         raux_dc         => raux_dc,
         rdat_dc         => rdat_dc,
         rdst_ix_dc      => rdst_ix_dc,
         rptr_dc         => rptr_dc
      );
   dcbr_wraccs_mux_i : dcbr_wraccess_mux
      PORT MAP (
         dram_address_a => dram_address_a,
         dram_byteena_a => dram_byteena_a,
         dram_data_a    => dram_data_a,
         dram_wren_a    => dram_wren_a,
         obj_init_addr  => obj_init_addr,
         obj_init_data  => obj_init_data,
         obj_init_wr    => obj_init_wr,
         ram_addr_me    => ram_addr_me,
         ram_byteena_me => ram_byteena_me,
         ram_wdata_me   => ram_wdata_me,
         ram_wren_me    => ram_wren_me
      );
   decoder_i : decoder
      PORT MAP (
         pc          => pc_if,
         instruction => if_instr,
         rdat_ix     => rdat_ix,
         rptr_ix     => rptr_ix,
         raux_ix     => raux_ix,
         csr_ix      => csr_ix,
         rdst_ix     => rdst_ix_dc_u,
         imm         => imm_dc_u,
         ctr_sig     => ctrl_dc_u,
         sbt_valid   => sbt_valid,
         sbt         => sbt
      );
   dram : dual_port_memory
      PORT MAP (
         address_a => ram_addr_me,
         address_b => ram_addr_at,
         byteena_a => ram_byteena_me,
         byteena_b => byteena_b,
         clock     => clk,
         data_a    => ram_wdata_me,
         data_b    => data_b,
         wren_a    => ram_wren_me,
         wren_b    => wren_b,
         q_a       => ram_rdata_me,
         q_b       => ram_rdata_at
      );
   dbu_i : dyn_branch_unit
      PORT MAP (
         imm       => imm_dc,
         alu_flags => flags,
         ctrl_sig  => ctrl_dc,
         pc        => pc_dc,
         dbt_valid => dbt_valid,
         dbt       => dbt
      );
   ex_reg_i : ex_reg
      PORT MAP (
         alu_out_ex_u   => alu_out_ex_u,
         clk            => clk,
         ctrl_dc        => ctrl_dc,
         imm_dc         => imm_dc,
         obj_init_stall => obj_init_stall,
         ptr_addr_ex_u  => ptr_addr_ex_u,
         raux_dc        => raux_dc,
         rdat_dc        => rdat_dc,
         rdst_ix_dc     => rdst_ix_dc,
         res_n          => res_n,
         rptr_dc        => rptr_dc,
         alu_out_dc_uq  => alu_out_dc_uq,
         alu_out_ex     => alu_out_ex,
         ctrl_dc_uq     => ctrl_dc_uq,
         ctrl_ex        => ctrl_ex,
         imm_ex         => imm_ex,
         raux_dc_uq     => raux_dc_uq,
         raux_ex        => raux_ex,
         rdat_ex        => rdat_ex,
         rdst_ix_ex     => rdst_ix_ex,
         rptr_dc_uq     => rptr_dc_uq,
         rptr_ex        => rptr_ex
      );
   if_reg_i : if_reg
      PORT MAP (
         clk            => clk,
         dbt_valid      => dbt_valid,
         if_instr_d     => if_instr_d,
         obj_init_stall => obj_init_stall,
         pc_current_pc  => pc_current_pc,
         res_n          => res_n,
         sbt_valid      => sbt_valid,
         if_instr       => if_instr,
         pc_if          => pc_if
      );
   irom_i : instruction_rom
      PORT MAP (
         pc    => current_pc_d,
         clock => clk,
         q     => if_instr_d
      );
   me_reg_i : me_reg
      PORT MAP (
         alu_out_ex     => alu_out_ex,
         clk            => clk,
         ctrl_ex        => ctrl_ex,
         imm_ex         => imm_ex,
         mem_out_me_u   => mem_out_me_u,
         obj_init_stall => obj_init_stall,
         raux_ex        => raux_ex,
         rdat_ex        => rdat_ex,
         rdst_ix_ex     => rdst_ix_ex,
         res_n          => res_n,
         rptr_ex        => rptr_ex,
         alu_out_me     => alu_out_me,
         at_mode_me     => at_mode_me,
         ctrl_me        => ctrl_me,
         imm_me         => imm_me,
         mem_out_me     => mem_out_me,
         mem_out_me_uq  => mem_out_me_uq,
         raux_me        => raux_me,
         rdat_me        => rdat_me,
         rdst_ix_me     => rdst_ix_me,
         rptr_me        => rptr_me
      );
   next_pc_mux_i : next_pc_mux
      PORT MAP (
         incremented_pc    => incremented_pc,
         static_branch_pc  => sbt,
         dynamic_branch_pc => dbt,
         dbta_valid        => dbt_valid,
         sbta_valid        => sbt_valid,
         next_pc           => current_pc_d
      );
   obj_init_fsm_i : obj_init_fsm
      PORT MAP (
         alu_out_ex     => alu_out_ex,
         clk            => clk,
         ctrl_ex        => ctrl_ex,
         end_addr       => end_addr,
         imm_ex         => imm_ex,
         raux_ex        => raux_ex,
         rdat_ex        => rdat_ex,
         res_n          => res_n,
         rptr_ex        => rptr_ex,
         obj_init_addr  => obj_init_addr,
         obj_init_data  => obj_init_data,
         obj_init_stall => obj_init_stall,
         obj_init_wr    => obj_init_wr
      );
   pc_increment_i : pc_incrementer
      PORT MAP (
         pc      => pc_current_pc,
         next_pc => incremented_pc
      );
   pc_reg_i : pc_reg
      PORT MAP (
         clk            => clk,
         current_pc_d   => current_pc_d,
         obj_init_stall => obj_init_stall,
         res_n          => res_n,
         pc_current_pc  => pc_current_pc
      );
   pgu_i : pgu
      PORT MAP (
         imm      => imm_dc,
         pgu_mode => pgu_mode_dc,
         raux     => raux_dc,
         rdat     => rdat_dc,
         rptr     => rptr_dc,
         addr     => ptr_addr_ex_u
      );
   register_file_i : register_file
      PORT MAP (
         clk     => clk,
         res_n   => res_n,
         rdat_ix => rdat_ix,
         rptr_ix => rptr_ix,
         raux_ix => raux_ix,
         rdat    => rdat_rf,
         rptr    => rptr_rf,
         raux    => raux_rf,
         rd_wb   => rd_wb
      );

END struct;
