-- VHDL Entity riscvio_lib.riscvio_soc.symbol
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 17:29:04 07.07.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY riscvio_soc IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      rx    : IN     std_logic;
      tx    : OUT    std_logic
   );

-- Declarations

END riscvio_soc ;

