--
-- VHDL Architecture riscvio_lib.riscvio_tb.struct
--
-- Created:
--          by - rbnlux.ckoehler (pc037)
--          at - 16:18:48 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY riscvio_lib;

ARCHITECTURE struct OF riscvio_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL res_n : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen_var
   GENERIC (
      ONTIME    : time := 10 ns;
      OFFTIME   : time := 10 ns;
      RESETTIME : time := 35 ns
   );
   PORT (
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT riscvio
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen_var USE ENTITY riscvio_lib.clk_res_gen_var;
   FOR ALL : riscvio USE ENTITY riscvio_lib.riscvio;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : clk_res_gen_var
      GENERIC MAP (
         ONTIME    => 10 ns,
         OFFTIME   => 10 ns,
         RESETTIME => 35 ns
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_1 : riscvio
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );

END struct;
