-- VHDL Entity riscvio_lib.riscvio_soc_tb.symbol
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 16:38:55 30.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY riscvio_soc_tb IS
-- Declarations

END riscvio_soc_tb ;

