-- VHDL Entity cyclone10gxlib.simple_ram_proc_interface.symbol
--
-- Created:
--          by - leylknci.meyer (pc024)
--          at - 11:27:20 05/17/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE ieee.math_real.all;
LIBRARY rv64i_lib;
USE rv64i_lib.interface.ALL;
USE rv64i_lib.isa.ALL;
USE rv64i_lib.ic.ALL;

ENTITY simple_ram_proc_interface IS
   GENERIC( 
      BASE_ADDR : natural := 65536;
      SIZE      : natural := 8192
   );
   PORT( 
      io_addr      : IN     dword;
      io_addr_u    : IN     dword;
      io_mode      : IN     mem_mode_type;
      io_wdata     : IN     dword;
      q            : IN     std_logic_vector (63 DOWNTO 0);
      address      : OUT    std_logic_vector (positive(ceil(log2(real(SIZE / BYTE_WIDTH))))-1  DOWNTO 0);
      byteena      : OUT    std_logic_vector (7 DOWNTO 0);
      rdata        : OUT    dword;
      rdata_active : OUT    boolean;
      wdata        : OUT    std_logic_vector (63 DOWNTO 0);
      wena         : OUT    std_logic
   );

-- Declarations

END simple_ram_proc_interface ;

