-- VHDL Entity riscvio_lib.stall_logic.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 21:40:08 23.06.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
USE riscvio_lib.caches.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;
USE riscvio_lib.caches.all;

ENTITY stall_logic IS
   PORT( 
      ic_stall       : IN     boolean;
      obj_init_stall : IN     boolean;
      stall          : OUT    boolean
   );

-- Declarations

END stall_logic ;

