-- VHDL Entity riscvio_lib.stall_logic.interface
--
-- Created:
--          by - rbnlux.ckoehler (pc023)
--          at - 14:56:10 06/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
USE riscvio_lib.pipeline.all;
LIBRARY altera_mf;
USE altera_mf.altera_mf_components.all;
USE riscvio_lib.pipeline.all;

ENTITY stall_logic IS
   PORT( 
      ac_stall       : IN     boolean;
      dc_stall       : IN     boolean;
      ic_stall       : IN     boolean;
      obj_init_stall : IN     boolean;
      stall          : OUT    boolean
   );

-- Declarations

END stall_logic ;

