-- VHDL Entity riscvio_lib.stall_logic.interface
--
-- Created:
--          by - surfer.UNKNOWN (SURFER-A0000001)
--          at - 17:28:57 07.07.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;
USE riscvio_lib.pipeline.all;

ENTITY stall_logic IS
   PORT( 
      ac_stall       : IN     boolean;
      clk            : IN     std_logic;
      dc_stall       : IN     boolean;
      ebreak_stall   : IN     boolean;
      ic_stall       : IN     boolean;
      io_stall_int   : IN     boolean;
      obj_init_stall : IN     boolean;
      res_n          : IN     std_logic;
      stall          : OUT    boolean
   );

-- Declarations

END stall_logic ;

