--
-- VHDL Architecture riscvio_lib.decoder_tb.struct
--
-- Created:
--          by - leylknci.meyer (pc038)
--          at - 19:03:12 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY riscvio_lib;
USE riscvio_lib.isa.all;


ARCHITECTURE struct OF decoder_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk         : std_logic;
   SIGNAL ctr_sig     : ctrl_sig_t;
   SIGNAL instruction : std_logic_vector(31 DOWNTO 0);
   SIGNAL res_n       : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen_var
   GENERIC (
      ONTIME    : time := 10 ns;
      OFFTIME   : time := 10 ns;
      RESETTIME : time := 35 ns
   );
   PORT (
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT decoder
   PORT (
      instruction : IN     std_logic_vector (31 DOWNTO 0);
      ctr_sig     : OUT    ctrl_sig_t 
   );
   END COMPONENT;
   COMPONENT decoder_tester
   PORT (
      clk         : IN     std_logic ;
      res_n       : IN     std_logic ;
      instruction : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen_var USE ENTITY riscvio_lib.clk_res_gen_var;
   FOR ALL : decoder USE ENTITY riscvio_lib.decoder;
   FOR ALL : decoder_tester USE ENTITY riscvio_lib.decoder_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : clk_res_gen_var
      GENERIC MAP (
         ONTIME    => 10 ns,
         OFFTIME   => 10 ns,
         RESETTIME => 35 ns
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_2 : decoder
      PORT MAP (
         instruction => instruction,
         ctr_sig     => ctr_sig
      );
   U_1 : decoder_tester
      PORT MAP (
         clk         => clk,
         res_n       => res_n,
         instruction => instruction
      );

END struct;
