-- VHDL Entity riscvio_lib.wb_reg.generatedInstance
--
-- Created:
--          by - leylknci.meyer (pc038)
--          at - 16:59:38 04/24/24
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY wb_reg IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic
   );

END wb_reg ;

